config/routes.rb
Rails.application.routes.draw do

  #管理者ルーティング
  devise_for :admin,skip: [:registrations, :passwords], controllers: {
  sessions:      'admin/sessions'
  }


  namespace :admin do
    resources :members, only: [:index, :show, :edit, :update]
    resources :order_items, only: [:update]
    resources :genres, only: [:index, :edit, :create, :update]
    resources :items, only: [:index, :edit, :create, :update, :new, :show]
    resources :orders, only: [:update, :show]
    root to: 'homes#top'
  end

  # 顧客ルーティング
  devise_for :members,skip: [:passwords], controllers: {
  sessions:      'public/sessions',
  registrations: 'public/registrations'
  }



  scope module: :public do
   root to: "homes#top"
   get 'about' => 'homes#about'
   get 'member/edit' => 'members#edit'
   patch 'member' => 'members#update'
    resource :members, only: [:show] do
    collection do
      get 'unsubscribe'
      patch 'withdraw'
    end
   end
   resources :cart_items, only: [:index, :create, :update, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end
   resources :shipping_addresses, only: [:index, :create, :destroy, :edit, :update ]
   resources :orders, only: [:new, :create, :index, :show] do
     collection do
       post 'confirm'
       get 'complete'
      end
    end
   resources :items, only: [:index, :show]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :member
  belongs_to :item
  
  ## 小計を求めるメソッド
def subtotal
    item.add_tax_non_taxed_price * item_quantity
end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_items

  def add_tax_non_taxed_price
  (self.non_taxed_price * 1.10).round
  end
   #imageが保存されていないために起きるエラーを回避する記述
   def get_image
    if image.attached?
      image
    else
      'no_image.jpg'
    end
   end

end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :shipping_addresses
  has_many :order_items
  has_many :orders

 def active_for_authentication?
    super && (user_status == true)
 end

 # 会員フルネーム
 def full_name
   self.first_name + " " + self.last_name
 end

 # 会員カナフルネーム
 def kana_full_name
   self.first_name_kana + " " + self.last_name_kana
 end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :member
  has_many :order_items, dependent: :destroy
  
   #0:クレジットカード、1:銀行振込
  enum payment_method: { credit_card: 0, transfer: 1 }
   #0:入金待ち、1:入金確認、2:製作中、3:発送準備中、4:発送済み
  enum request_status: { wait: 0, confirm: 1, product: 2, ready: 3, sent: 4 }

  def add_tax_non_taxed_price
  (self.non_taxed_price * 1.10).round
  end

  ## 小計を求めるメソッド
  def subtotal
    item.add_tax_non_taxed_price * item_quantity
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item
  
  # 制作ステータス（0:着手不可  1:製作待ち  2:製作中  3:製作完了）
  enum production_status: {impossible:0, wait:1, inproduction:2, complete:3 }

end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
  belongs_to :member

  # Addressモデル
  def full_address
    '〒' + delivery_code.to_s + ' ' + delivery_address.to_s + ' ' + address.to_s
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

def index
  @genre = Genre.new
  @genres = Genre.all
end

def create
  @genre = Genre.new(genre_params)
  @genre.save
  redirect_to admin_genres_path
end

def edit
  @genre = Genre.find(params[:id])
end

def update
  @genre = Genre.find(params[:id])
  @genre.update(genre_params)
    redirect_to admin_genres_path
end

private

def genre_params
  params.require(:genre).permit(:name)
end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @orders = Order.all.page(params[:page]).per(10)
    @order_items = OrderItem.all
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all.page(params[:page]).per(10)
  end

  def create
    item = Item.new(item_params)
    item.save
    redirect_to admin_item_path(item.id)
  end

  def new
    @item = Item.new(params[:id])
  end

  def edit
     @item = Item.find(params[:id])
  end

  def show
     @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path(item.id)
  end

  private

  def item_params
    params.require(:item).permit(:name, :explanation, :non_taxed_price, :sales_status, :image, :genre_id)
  end
end

app/controllers/admin/members_controller.rb
class Admin::MembersController < ApplicationController
  def index
    @members = Member.page(params[:page]).per(5)
  end

  def show
    @member = Member.find(params[:id])
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
   @member = Member.find(params[:id])
    if @member.update(member_params)
       redirect_to admin_member_path(@member.id)
    else
       render :edit
    end
  end

  private

  def member_params
    params.require(:member).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :zip_code, :address, :phone_number, :email, :user_status )
  end


end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def show
     @order = Order.find(params[:id])
     @order_items = @order.order_items
  end

  def update
    @order = Order.find(params[:id])
    order_items = @order.order_items
    @order.update(order_params)
    if @order.request_status == "confirm"
      order_items.update_all(production_status: "wait")
    end
    redirect_to admin_order_path(@order.id)
  end

private

  def order_params
    params.require(:order).permit(:request_status)
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_root_path
    when Member
      members_path(current_member)
    end
  end

  def after_sign_out_path_for(resource)
    case resource
    when :admin
      new_admin_session_path
    when :member
      root_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :first_name_kana, :last_name_kana, :zip_code, :address, :phone_number])
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
    <div class="row">
        <div clas="col-12">
            <div class="my-4">
    　        <h3 class="bg-light d-flex align-items-center justify-content-center w-75">ジャンル編集</h3>
   　      　</div>
            <%= form_with url: admin_genre_path(@genre), model: @genre do |f| %>
                <table class="table table-borderless">
                    <tr>
                        <th>ジャンル名</th>
                        <th><%= f.text_field :name, placeholder:"ジャンル名" %></th>
                        <td><%= f.submit "変更を保存", class:"btn btn-success" %></td>
                    </tr>
                </table>
            <% end %>
        </div>
    </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row">
    <div clas="col-12">
　　　<div class="my-4">
    　<h2 class="bg-light d-flex align-items-center justify-content-center w-75">ジャンル一覧・追加</h2>
   　　</div>
        <%= form_with url: admin_genres_path(@genre), model: @genre do |f| %>
         <table class="table table-borderless">
            <tr>
              <th>ジャンル名</th>
              <th><%= f.text_field :name, placeholder:"ジャンル名" %></th>
              <td><%= f.submit "新規登録", class:"btn btn-success" %></td>
            </tr>
         </table>
        </div>
    　</div>
         <% end %>
         <div class="row">
            <table class="table">
              <thead>
                <tr>
                  <th class="bg-light">ジャンル</th>
                  <th colspan="3"></th>
                </tr>
              </thead>
              <% @genres.each do |genre| %>
                 <tr>
                  <th><%= genre.name %></th>
                  <td><%= link_to "編集する", edit_admin_genre_path(genre), class:"btn btn-success py-1" %></td>
                </tr>
              <% end %>
            </table>
         </div>
      </div>

app/views/admin/items/create.html.erb
<h1>Admin::Items#create</h1>
<p>Find me in app/views/admin/items/create.html.erb</p>

app/views/admin/items/edit.html.erb
<div class="container">
	  <div class="row ml-3 mb-5 mt-3">
      <h2 class="head-line title_h2 text-left bg-light d-inline-block">商品編集</h2>
    </div>
  <div class="col-md-6 offset-md-3">
<%= form_with model: @item, url:admin_item_path(@item.id) do |f| %>
<table>
 <tr>
  <th>商品画像</th>
  <td><%= f.file_field :image, placeholder:"商品画像", accept: "image/*"%></td>
 </tr>
 <tr>
  <th>商品名</th>
  <td><%= f.text_field :name %></td>
 </tr>
 <tr>
  <th>商品説明</th>
  <td><%= f.text_area :explanation, size: 25 %></td>
 </tr>
 <tr>
  <th>ジャンル</th>
  <td><%= f.collection_select :genre_id, Genre.all, :id, :name %></td>
 </tr>
 <tr>
  <th>税抜価格</th>
  <td><%= f.text_field :non_taxed_price %>円</td>
 </tr>
 <tr>
  <th>販売ステータス</th>
  <td><%= f.select :sales_status, {"販売中": true, "販売停止中": false} %></td>
 </tr>
</table>
　<div class="d-grid gap-2 col-6 mx-auto">
  　<%= f.submit '変更を保存', class: "btn btn-success" %>
  </div>
  <% end %>
 　</div>
 </div>

app/views/admin/items/index.html.erb
<div class="container">
	  <div class="row ml-3 mb-5 mt-3">
      <h2 class="head-line title_h2 text-left bg-light d-inline-block">商品一覧</h2>
    </div>
　<%= link_to new_admin_item_path, method: :get, class: "btn btn-default" do %>
    <i class="fas fa-plus-circle fa-2x"></i>
  <% end %>
<table class="table">
  <thead>
    <tr>
      <th>商品ID</th>
      <th>商品名</th>
      <th>税抜価格</th>
      <th>ジャンル</th>
      <th>ステータス</th>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
    <tr>
     <td><%= item.id %></td>
     <td><%= link_to item.name, admin_item_path(item.id) %></td>
     <td><%= item.non_taxed_price.to_s(:delimited) %></td>
     <td><%= item.genre.name %></td>
     <td>
    <% if item.sales_status == true %>
     <a class="text-success font-weight-bold">販売中</a>
    <% else %>
     <a>販売停止中</a>
	<% end %>
     </td>
     </tr>
    <% end %>
  </tbody>
</table>
　<ul class="pagination justify-content-center">
   <%= paginate @items %>
  </ul>
</div>

app/views/admin/items/new.html.erb
<div class="container">
	  <div class="row ml-3 mb-5 mt-3">
      <h2 class="head-line title_h2 text-left bg-light d-inline-block">商品新規登録</h2>
    </div>
  <div class="col-md-6 offset-md-3">
  <%= form_with model: @item, url:admin_items_path do |f| %>
  　<div class="form-group" >
      <%= f.label :image, '商品画像' %>

      <%= f.file_field :image, placeholder:"商品画像", accept:"image/*" %>

    </div>
    <div class="form-group" >
      <%= f.label :name, '商品名' %>
      <%= f.text_field :name, placeholder:"商品名" %>
    </div>
    <div class="form-group">
      <%= f.label :explanation, '商品説明' %>
      <%= f.text_area :explanation, placeholder:"ここに説明文を記述します" %>
    </div>
    <div class="form-group">
      <%= f.label :genre_id, 'ジャンル' %>
      <%= f.collection_select :genre_id, Genre.all, :id, :name, {prompt: "--選択してください--"} %>
    </div>
    <div class="form-group">
      <%= f.label :non_taxed_price, '税抜価格' %>
      <%= f.text_field :non_taxed_price, placeholder:"1000" %>円
    </div>
    <div class="form-group">
      <%= f.label :sales_status, '販売ステータス' %>
      <%= f.radio_button :sales_status, true %>
      <%= f.label :sales_status, '販売中' %>
      <%= f.radio_button :sales_status, false %>
      <%= f.label :sales_status, '販売停止中' %>
    </div>
  <div class="d-grid gap-2 col-6 mx-auto">
   <%= f.submit "新規登録" , class: "btn btn-success"  %>
  </div>
 <% end %>
 </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row ml-3 mb-5 mt-3">
   <h2 class="head-line title_h2 text-left bg-light d-inline-block">商品詳細</h2>
  </div>
 <div class="row">
   <div class="col-lg-4">
     <%= image_tag @item.image, size: "300x200" %>
   </div>
<div class="col-lg-8">
 <table>
  <tr>
    <th>商品名</th>
    <td><%= @item.name %></td>
  </tr>
  <tr>
    <th>商品説明</th>
    <td><%= @item.explanation %></td>
  </tr>
  <tr>
    <th>ジャンル</th>
    <td><%= @item.genre.name %></td>
  </tr>
  <tr>
    <th>税込価格<br>
      （税抜価格）</th>
    <td><%= @item.add_tax_non_taxed_price.to_s(:delimited) %>（<%= @item.non_taxed_price %>）円</td>
  </tr>
  <tr>
    <th>販売ステータス</th>
    <td>
      <% if @item.sales_status == true %>
        <a class="text-success font-weight-bold">販売中</a>
      <% else %>
        <a class="text-secondary">販売停止中</a>
      <% end %>
    </td>
  </tr>
</table>
<div class="d-grid gap-2 col-6 mx-auto">
 <%= link_to "編集する", edit_admin_item_path(@item.id), class: "btn btn-success" %>
 </div>
 </div>
</div>

app/views/admin/items/update.html.erb
<h1>Admin::Items#update</h1>
<p>Find me in app/views/admin/items/update.html.erb</p>

app/views/admin/members/edit.html.erb
<div class="container">
    <div class="row ml-3 mb-5 mt-3">
    <h2 class="head-line title_h2 text-left bg-light d-inline-block"><%= @member.last_name %> <%= @member.first_name %>さんの会員情報編集</h2>
    </div>

      <%= form_with model:@member, url:admin_member_path, local:true do |f| %>
       <div class="form-group row">
            <%= f.label :"会員id", class: "col-md-3" %>
            <%= @member.id %>
        </div>

        <div class="form-group row">
            <%= f.label :"氏名", class: "col-md-3" %>
            <%= f.text_field :last_name, class: "form-control name col-md-4" %>
            <%= f.text_field :first_name, class: "form-control name col-md-4 offset-md-1" %>
        </div>

        <div class="form-group row">
            <%= f.label :"フリガナ", class: "col-md-3" %>
            <%= f.text_field :last_name_kana, class: "form-control name col-md-4" %>
            <%= f.text_field :first_name_kana, class: "form-control name col-md-4 offset-md-1" %>
        </div>


        <div class="form-group row">
            <%= f.label :"郵便番号",class: "col-md-3" %>
            <%= f.text_field :zip_code, class: "form-control name col-md-9" %>
        </div>

        <div class="form-group row">
            <%= f.label :"住所",class: "col-md-3" %>
            <%= f.text_field :address, class: "form-control name col-md-9" %>
        </div>

        <div class="form-group row">
            <%= f.label :"電話番号",class: "col-md-3" %>
            <%= f.text_field :phone_number, class: "form-control name col-md-9" %>
        </div>

        <div class="form-group row">
            <%= f.label :"メールアドレス",class: "col-md-3" %>
            <%= f.text_field :email, class: "form-control name col-md-9" %>
        </div>

         <div class="form-group row">
            <%= f.label :"会員ステータス",class: "col-md-3" %>
            <%= f.radio_button :user_status, true, class:"m-1" %>
            <%= f.label :user_status, "有効" %>
            <%= f.radio_button :user_status, false, class:"m-1" %>
            <%= f.label :user_status, "退会" %>
        </div>

        <div class="form-group row">
           <%= f.submit "変更内容を保存", class: 'btn btn-success ' %>
        </div>




     <% end %>
</div>

app/views/admin/members/index.html.erb
<div class="container">
	  <div class="row ml-3 mb-5 mt-3">
    <h2 class="head-line title_h2 text-left bg-light d-inline-block">会員一覧</h2>
    </div>

    <table class='table table-hover table-inverse'>
      <thead>
       <tr>
        <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
        <th>ステータス</th>
       </tr>
      </thead>
      <tbody>
        <% @members.each do |member| %>
        <tr>
          <td><%= member.id %></td>
          <td><%= link_to admin_member_path(member.id) do %>
            <%= member.last_name %> <%= member.first_name %>
            <% end %>
          </td>
          <td><%= member.email %></td>
          <td>
            <% if member.user_status == true %>
            <p class= 'text-success'>有効</p>
            <% else %>
            <p class= 'text-danger'>退会</p>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
      </table>
      <ul class="pagination justify-content-center">
      <%= paginate @members %>
      </ul>
</div>

app/views/admin/members/show.html.erb
<div class="container">
	  <div class="row ml-3 mb-5 mt-3">
    <h2 class="head-line title_h2 text-left bg-light d-inline-block"><%= @member.last_name %> <%= @member.first_name %>さんの会員詳細</h2>
    </div>

    <table class='table table table-borderless'>
    <tr>
      <td>会員ID</td>
      <td><%= @member.id %></td>
    </tr>
    <tr>
      <td>氏名</td>
      <td><%= @member.last_name %> <%= @member.first_name %></td>
    </tr>
    <tr>
      <td>フリガナ</td>
      <td><%= @member.last_name_kana %> <%= @member.first_name_kana %></td>
    </tr>
    <tr>
      <td>郵便番号</td>
      <td><%= @member.zip_code %></td>
    </tr>
    <tr>
      <td>住所</td>
      <td><%= @member.address %></td>
    </tr>
    <tr>
      <td>電話番号</td>
      <td><%= @member.phone_number %></td>
    </tr>
    <tr>
      <td>メールアドレス</td>
      <td><%= @member.email %></td>
    </tr>
    <tr>
      <td>会員ステータス</td>
      <td>
      <% if @member.user_status == true %>
      <p class= 'text-success'>有効</p>
       <% else %>
       <p class= 'text-danger'>退会</p>
      <% end %>
      </td>
    </tr>
    </table>

    <div class="actions">
  		<%= link_to "編集する", edit_admin_member_path, class:"btn btn btn-success" %>
  	  <%= link_to " 注文履歴を見る", admin_root_path,  class:"btn btn btn-primary" %>
    </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
      <h2 class="head-line title_h2 text-left bg-light d-inline-block">注文履歴詳細</h2>
    </div>
  <table>
   <tr>
   <th>購入者</th>
   <!--余裕があれば購入者の購入履歴へのリンクをつける-->
    <td><%= @order.member.last_name + @order.member.first_name %></td>
   </tr>
   <tr>
   <th>注文日</th>
    <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
   </tr>
   <tr>
   <th>配送先</th>
    <td>〒<%= @order.delivery_code + @order.delivery_address %></td>
   </tr>
   <tr>
   <th></th>
    <td><%= @order.member.last_name + @order.member.first_name %></td>
   </tr>
   <tr>
   <th>支払方法</th>
    <td><%= @order.payment_method_i18n %></td>
   </tr>
   <tr>
   <th>注文ステータス</th>
   <td>
     <%= form_with model: @order, url: admin_order_path(@order.id) do |f| %>
      <%= f.select :request_status, Order.request_statuses.keys.map {|k| [Order.request_statuses_i18n[k], k]} %>
      <%= f.submit '更新', class: 'btn btn-success' %>
     <% end %>
   </td>
   </tr>
  </table>
 </div>
</div>
<div class="container">
 <div class="row d-flex align-items-end">
  <div class="col-md-8">
   <table class="table border-bottom">
   <thead>
     <tr>
      <th>商品名</th>
      <th>単価(税込)</th>
      <th>数量</th>
      <th>小計</th>
      <th>製作ステータス</th>
     </tr>
   </thead>
   <tbody>
    <% @order_items.each do |order_item| %>
      <tr>
        <td><%= order_item.item.name %></td>
        <td><%= order_item.item.add_tax_non_taxed_price.to_s(:delimited) %></td>
        <td><%= order_item.item_quantity %></td>
        <td><%= (order_item.item.add_tax_non_taxed_price * order_item.item_quantity).to_s(:delimited) %></td>
        <td>
         <%= form_with model: order_item, url: admin_order_item_path(order_item.id) do |f| %>
          <%= f.select :production_status, OrderItem.production_statuses.keys.map {|k| [OrderItem.production_statuses_i18n[k], k]} %>
          <%= f.submit '更新', class: 'btn btn-success' %>
         <% end %>
        </td>
       </tr>
    <% end %>
   </tbody>
  </table>
 </div>
 <div class="col-md-4">
  <table>
   <tr>
     <th>商品合計</th>
     <td><%= @order.invoice_amount.to_s(:delimited) %>円</td>
   </tr>
   <tr>
     <th>送料</th>
     <td> <%= @order.postage %>円</td>
    </tr>
    <tr>
     <th>請求金額合計</th>
     <td><%= (@order.invoice_amount + @order.postage).to_s(:delimited) %>円</td>
    </tr>
  </table>
  </div>
 </div>
 </div>
 </div>