config/routes.rb
Rails.application.routes.draw do

  #管理者ルーティング
  devise_for :admin,skip: [:registrations, :passwords], controllers: {
  sessions:      'admin/sessions'
  }


  namespace :admin do
    resources :members, only: [:index, :show, :edit, :update]
    resources :order_items, only: [:update]
    resources :genres, only: [:index, :edit, :create, :update]
    resources :items, only: [:index, :edit, :create, :update, :new, :show]
    resources :orders, only: [:update, :show]
    root to: 'homes#top'
  end

  # 顧客ルーティング
  devise_for :members,skip: [:passwords], controllers: {
  sessions:      'public/sessions',
  registrations: 'public/registrations'
  }



  scope module: :public do
   root to: "homes#top"
   get 'about' => 'homes#about'
   get 'member/edit' => 'members#edit'
   patch 'member' => 'members#update'
    resource :members, only: [:show] do
    collection do
      get 'unsubscribe'
      patch 'withdraw'
    end
   end
   resources :cart_items, only: [:index, :create, :update, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end
   resources :shipping_addresses, only: [:index, :create, :destroy, :edit, :update ]
   resources :orders, only: [:new, :create, :index, :show] do
     collection do
       post 'confirm'
       get 'complete'
      end
    end
   resources :items, only: [:index, :show]
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :member
  belongs_to :item
  
  ## 小計を求めるメソッド
def subtotal
    item.add_tax_non_taxed_price * item_quantity
end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image

  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_items

  def add_tax_non_taxed_price
  (self.non_taxed_price * 1.10).round
  end
   #imageが保存されていないために起きるエラーを回避する記述
   def get_image
    if image.attached?
      image
    else
      'no_image.jpg'
    end
   end

end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :shipping_addresses
  has_many :order_items
  has_many :orders

 def active_for_authentication?
    super && (user_status == true)
 end

 # 会員フルネーム
 def full_name
   self.first_name + " " + self.last_name
 end

 # 会員カナフルネーム
 def kana_full_name
   self.first_name_kana + " " + self.last_name_kana
 end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :member
  has_many :order_items, dependent: :destroy
  
   #0:クレジットカード、1:銀行振込
  enum payment_method: { credit_card: 0, transfer: 1 }
   #0:入金待ち、1:入金確認、2:製作中、3:発送準備中、4:発送済み
  enum request_status: { wait: 0, confirm: 1, product: 2, ready: 3, sent: 4 }

  def add_tax_non_taxed_price
  (self.non_taxed_price * 1.10).round
  end

  ## 小計を求めるメソッド
  def subtotal
    item.add_tax_non_taxed_price * item_quantity
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item
  
  # 制作ステータス（0:着手不可  1:製作待ち  2:製作中  3:製作完了）
  enum production_status: {impossible:0, wait:1, inproduction:2, complete:3 }

end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
  belongs_to :member

  # Addressモデル
  def full_address
    '〒' + delivery_code.to_s + ' ' + delivery_address.to_s + ' ' + address.to_s
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

def index
  @genre = Genre.new
  @genres = Genre.all
end

def create
  @genre = Genre.new(genre_params)
  @genre.save
  redirect_to admin_genres_path
end

def edit
  @genre = Genre.find(params[:id])
end

def update
  @genre = Genre.find(params[:id])
  @genre.update(genre_params)
    redirect_to admin_genres_path
end

private

def genre_params
  params.require(:genre).permit(:name)
end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @orders = Order.all.page(params[:page]).per(10)
    @order_items = OrderItem.all
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all.page(params[:page]).per(10)
  end

  def create
    item = Item.new(item_params)
    item.save
    redirect_to admin_item_path(item.id)
  end

  def new
    @item = Item.new(params[:id])
  end

  def edit
     @item = Item.find(params[:id])
  end

  def show
     @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path(item.id)
  end

  private

  def item_params
    params.require(:item).permit(:name, :explanation, :non_taxed_price, :sales_status, :image, :genre_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_root_path
    when Member
      members_path(current_member)
    end
  end

  def after_sign_out_path_for(resource)
    case resource
    when :admin
      new_admin_session_path
    when :member
      root_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :first_name_kana, :last_name_kana, :zip_code, :address, :phone_number])
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_header.html.erb
<header>
<!-- 管理者がログインしている時 -->
  <% if admin_signed_in? %>
    <nav class="navbar navbar-expand-lg">
        <span class="navbar-brand">
          <%= link_to root_path do %>
            <%= image_tag 'Nagano.png', size: "200x50" %>
          <% end %>
        </span>
        <div class="collapse navbar-collapse">
          <ul class="navbar-nav ml-auto">
            <li class="mx-2"><%= link_to '商品一覧', admin_items_path, class:"nav-link text-dark" %></li>
            <li class="mx-2"><%= link_to '会員一覧', admin_members_path,class:"nav-link text-dark" %></li>
            <li class="mx-2"><%= link_to '注文履歴一覧', admin_root_path, class:"nav-link text-dark" %></li>
            <li class="mx-2"><%= link_to 'ジャンル一覧', admin_genres_path, class:"nav-link text-dark" %></li>
            <li class="mx-2"><%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class:"nav-link text-dark" %></li>
            <li class="mx-2">
              <!--<%= form_with local: true do |f| %>-->
              <!--  <%= f.text_field 'search[value]' %>-->
              <!--  <%= f.submit :"検索" %>-->
              <!--<% end %>-->
            </li>
          </ul>
        </div>
    </nav>
  <!--会員がログインしている時 -->
  <% elsif member_signed_in? %>
     <nav class="navbar navbar-expand-lg">
        <!--<div class="container">-->
          <span class="navbar-brand">
            <%= link_to root_path do %>
              <%= image_tag 'Nagano.png', size: "200x50" %>
            <% end %>
          </span>
            <!--<p class='ml-12'>ようこそ、<%= current_member.full_name %>さん！</p>-->
              <div class="collapse navbar-collapse">
                <ul class="navbar-nav ml-auto">
                  <li class="border mx-2"><%= link_to 'マイページ', members_path(current_member), class:"nav-link text-dark" %></li>
                  <li class="border mx-2"><%= link_to '商品一覧', items_path, class:"nav-link text-dark" %></li>
                  <li class="border mx-2"><%= link_to 'カート', cart_items_path, class:"nav-link text-dark" %></li>
                  <li class="border mx-2"><%= link_to 'ログアウト', destroy_member_session_path, method: :delete, class:"nav-link text-dark" %></li>
                  <li class="mx-2">
                    <%= form_with local: true do |f| %>
                      <%= f.text_field 'search[value]' %>
                      <%= f.submit :"検索" %>
                    <% end %>
                  </li>
                </ul>
              </div>
        <!--</div>-->
      </nav>
 <!-- ログインしていない時 -->
  <% else %>
    <nav class="navbar navbar-expand-lg">
        <span class="navbar-brand">
          <%= link_to root_path do %>
            <%= image_tag 'Nagano.png', size: "200x50" %>
          <% end %>
        </span>
          <div class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto">
              <li class="border mx-2"><%= link_to 'About', about_path, class:"nav-link text-dark" %></li>
              <li class="border mx-2"><%= link_to '商品一覧', items_path, class:"nav-link text-dark" %></li>
              <li class="border mx-2"><%= link_to '新規登録', new_member_registration_path, class:"nav-link text-dark" %></li>
              <li class="border mx-2"><%= link_to 'ログイン', new_member_session_path, class:"nav-link text-dark" %></li>
              <li class="mx-2">
                <%= form_with local: true do |f| %>
                  <%= f.text_field 'search[value]' %>
                  <%= f.submit :"検索" %>
                <% end %>
              </li>
            </ul>
          </div>
    </nav>
  <% end %>
  <p class="border-bottom"></p>
</header>

app/views/layouts/_search_side_bar.html.erb
<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th class="active text-center">ジャンル検索</th>
    </tr>
  </thead>
  <tbody>
    <% genres.each do |genre| %>
      <tr>
        <td><%= link_to genre.name, items_path(genre_id: genre.id), :style=>"color:black" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/header' %>

    <main>
    <%= yield %>
    </main>
   <footer>
      <div class="mt-5  border-top mg">
        <div class="row"></div>
      </div>
    </footer>
  </body>
</html>